- name: Hardening Production Linux Image
  hosts: all
  become: yes
  tasks:
    - name: Update all system packages
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install mandatory security and monitoring tools
      apt:
        name:
          - fail2ban
          - ufw
          - amazon-cloudwatch-agent
        state: present

    - name: Disable SSH Password Authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
